criterion:
  loss: diceloss
  scheduler: ReduceLROnPlateau
  optimizer: adam
data:
  ds_path: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\Dataset_BUSI_with_GT
  val_dataset: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\val_ds2
  imgsize: 128
  imgchan: 3
  classes: 1
  catagory: null
  dataset: BreastUS
logging:
  folder: .\config
meta:
  Name: Local branch ver1.1 with diceloss, one class
  modelname: TEST
  use_autocast: 0
  device: cuda:0
optimization:
  epochs: 100
  batchsize: 8
  lr: 0.001
  weight_decay: 1e-5
  train_accumulation_steps: 4
  k_fold: 5
  deep_supervise: false
  pos: false
save:
  save_frequency: 25
  save_state_dict: True
  savemodel: True
  run_formal: True
  direc: ./Model_Result
  savefig_resize: False
  threshold: 0.333