criterion:
  loss: bce
  scheduler: ReduceLROnPlateau
  optimizer: adamw
data:
  ds_path: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\Dataset_BUSI_with_GT
  val_dataset: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\val_ds2
  imgsize: 128
  imgchan: 3
  classes: 1
  catagory: null
  dataset: BreastUS
logging:
  folder: .\config
meta:
  Name: ResAttnModule_reduce_layer_L test2
  modelname: TransFPN_Module_Unet_L
  use_autocast: 0
  device: cuda:0
optimization:
  epochs: 200
  batchsize: 8
  lr: 0.001
  weight_decay: 1e-5
  train_accumulation_steps: 1
  k_fold: 5
  deep_supervise: false
  pos: false
save:
  save_frequency: 20
  save_valid_img: False
  save_state_dict: True
  savemodel: True
  run_formal: True
  direc: .\TotalResult_HAND\20220520\ResAttnModule_reduce_layer_L test2
  savefig_resize: False
  threshold: 0.333