criterion:
  loss: BCEDicePenalizeBorderLoss
#  loss: bce
  scheduler: ReduceLROnPlateau
  optimizer: adamw
data:
  ds_path: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\Dataset_BUSI_with_GT
  val_dataset: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\val_ds2
  imgsize: 128
  imgchan: 3
  classes: 1
  catagory: null
  dataset: BreastUS
logging:
  folder: .\config
meta:
  Name: None # Note this test for what
  modelname: medt
  TrainState: Pretrain # Pretrain/Train
  device: cuda:0
  LOAD_PRETRAIN_WEIGHT: False  # Whether load pretrain weight or not
optimization:
  epochs: 200
  batchsize: 8
  lr: 0.001
  weight_decay: 1e-5
  train_accumulation_steps: 4
  k_fold: 5
  pos: false
save:
  save_frequency: 0
  save_valid_img: True
  save_state_dict: True
  savemodel: True
  run_formal: True
  direc: .\TotalResult_HAND\20220908\None
  savefig_resize: False
  threshold: 0.333