criterion:
  loss: bce
  scheduler: ReduceLROnPlateau
  optimizer: adamw
data:
  ds_path: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\Dataset_BUSI_with_GT
  val_dataset: D:\Programming\AI&ML\(Dataset)breast Ultrasound lmage Dataset\archive\val_ds2
  imgsize: 128
  imgchan: 3
  classes: 1
  catagory: null
  dataset: BreastUS
logging:
  folder: .\config
meta:
  Name: <test> Deeplabv3Modified batchsize=16, accumulation=8
  modelname: Deeplabv3_Modified
  device: cuda:0
optimization:
  epochs: 200
  batchsize: 16
  lr: 0.001
  weight_decay: 1e-5
  train_accumulation_steps: 8
  k_fold: 5
  pos: false
save:
  save_frequency: 40
  save_valid_img: True
  save_state_dict: True
  savemodel: True
  run_formal: True
  direc: .\TotalResult_HAND\20220701\Deeplabv3Modified 16 batchsize
  savefig_resize: False
  threshold: 0.333